/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemahibernate;

import java.awt.Color;
import java.time.Period;
import java.time.*;
import java.time.format.*;

/**
 *
 * @author Filipe
 */
public class FormularioGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioGUI.class.getName());

    /**
     * Creates new form FormularioGUI
     */
    public FormularioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Matricula = new javax.swing.JLabel();
        jLabel_Nome = new javax.swing.JLabel();
        jLabel_DataNasc = new javax.swing.JLabel();
        jLabel_Tele = new javax.swing.JLabel();
        jLabel_Cpf = new javax.swing.JLabel();
        jLabel_Idade = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();
        jTextField6_Idade = new javax.swing.JTextField();
        jButton1_Cad = new javax.swing.JButton();
        jButton2_Buscar = new javax.swing.JButton();
        jButton3_Excluir = new javax.swing.JButton();
        jButton4_AluVelho = new javax.swing.JButton();
        jButton5_AluNovo = new javax.swing.JButton();
        jButton6_Listar = new javax.swing.JButton();
        jFormattedMat = new javax.swing.JFormattedTextField();
        jFormattedDataNasc = new javax.swing.JFormattedTextField();
        jFormattedTele = new javax.swing.JFormattedTextField();
        jFormattedCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de cadastro");

        jLabel_Matricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Matricula.setText("Matrícula:");

        jLabel_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Nome.setText("Nome:");

        jLabel_DataNasc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_DataNasc.setText("Data de Nascimento: ");

        jLabel_Tele.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Tele.setText("Telefone:");

        jLabel_Cpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Cpf.setText("CPF:");

        jLabel_Idade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Idade.setText("Idade:");

        jTextField_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_Nome.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Nome.setText("Nome...");
        jTextField_Nome.setToolTipText("");
        jTextField_Nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NomeFocusLost(evt);
            }
        });

        jTextField6_Idade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField6_Idade.setEnabled(false);

        jButton1_Cad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1_Cad.setText("Cadastrar");

        jButton2_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2_Buscar.setText("Buscar");

        jButton3_Excluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3_Excluir.setText("Excluir");

        jButton4_AluVelho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4_AluVelho.setText("Aluno mais velho");

        jButton5_AluNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5_AluNovo.setText("Aluno mais novo");

        jButton6_Listar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6_Listar.setText("Listar Alunos");

        try {
            jFormattedMat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedMat.setText("####");
        jFormattedMat.setToolTipText("####");
        jFormattedMat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        try {
            jFormattedDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedDataNasc.setToolTipText("  /  /    ");
        jFormattedDataNasc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jFormattedDataNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedDataNascFocusLost(evt);
            }
        });

        try {
            jFormattedTele.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTele.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        try {
            jFormattedCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Matricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedMat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Cpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_DataNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Tele)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTele, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jButton1_Cad)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_Buscar)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Idade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3_Excluir)
                                    .addComponent(jButton4_AluVelho))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5_AluNovo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6_Listar)))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Idade)
                            .addComponent(jTextField6_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Matricula)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nome)
                    .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DataNasc)
                    .addComponent(jFormattedDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Tele)
                    .addComponent(jFormattedTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cpf)
                    .addComponent(jFormattedCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Cad)
                    .addComponent(jButton2_Buscar)
                    .addComponent(jButton4_AluVelho)
                    .addComponent(jButton5_AluNovo)
                    .addComponent(jButton6_Listar))
                .addGap(18, 18, 18)
                .addComponent(jButton3_Excluir)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NomeFocusGained
        // TODO add your handling code here:
        if (jTextField_Nome.getText().equals("Nome...")){
            jTextField_Nome.setText("");
            jTextField_Nome.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_NomeFocusGained

    private void jTextField_NomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NomeFocusLost
        // TODO add your handling code here:
        if (jTextField_Nome.getText().equals("")){
            jTextField_Nome.setText("Nome...");
            jTextField_Nome.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_NomeFocusLost

    private void jFormattedDataNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedDataNascFocusLost
        // TODO add your handling code here:
        String textoDataNasc = jFormattedDataNasc.getText();
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        try{
            LocalDate dataNascimento = LocalDate.parse(textoDataNasc, formatador);
            atualizarCampoIdade(dataNascimento);
        } catch (DateTimeParseException e) {
            System.err.println("Erro ao converter a data: " + textoDataNasc + " - " + e.getMessage());
            jTextField6_Idade.setText("");
        }
    }//GEN-LAST:event_jFormattedDataNascFocusLost

    private void atualizarCampoIdade(LocalDate dataNasc) {
        if (dataNasc != null) {
            LocalDate dataAtual = LocalDate.now();
            if (dataNasc.isAfter(dataAtual)){
                jTextField6_Idade.setText("");
            } 
            int dataCalculada = Period.between(dataNasc,dataAtual).getYears();
            jTextField6_Idade.setText(String.valueOf(dataCalculada));
        }
        else {
            jTextField6_Idade.setText("");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Cad;
    private javax.swing.JButton jButton2_Buscar;
    private javax.swing.JButton jButton3_Excluir;
    private javax.swing.JButton jButton4_AluVelho;
    private javax.swing.JButton jButton5_AluNovo;
    private javax.swing.JButton jButton6_Listar;
    private javax.swing.JFormattedTextField jFormattedCPF;
    private javax.swing.JFormattedTextField jFormattedDataNasc;
    private javax.swing.JFormattedTextField jFormattedMat;
    private javax.swing.JFormattedTextField jFormattedTele;
    private javax.swing.JLabel jLabel_Cpf;
    private javax.swing.JLabel jLabel_DataNasc;
    private javax.swing.JLabel jLabel_Idade;
    private javax.swing.JLabel jLabel_Matricula;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Tele;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6_Idade;
    private javax.swing.JTextField jTextField_Nome;
    // End of variables declaration//GEN-END:variables
}
